### PR TITLE
update schema and validation to support 3 year retention

### LINKED ISSUE #787: Support setting log retention to 3 years
**Is your feature request related to a problem? Please describe.**

1096 days is a valid value for the retention period of Cloudwatch logs: 

> The number of days to retain the log events in the specified log group. Possible values are: 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, **1096**, 1827, 2192, 2557, 2922, 3288, and 3653.

From https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#CWL-PutRetentionPolicy-request-retentionInDays

But you cannot specify 1096 as a value for retention in days to the agent because the schema does not support it.

**Describe the solution you'd like**

Add 1096 days as a supported schema value for Cloudwatch log retention days to this agent.

**Describe alternatives you've considered**

None

### PR DESCRIPTION
**Pull request by markdboyd**
# Description of the issue

Closes #787 

1096 days is a valid value for Cloudwatch retention period in the console and CLI, but not in this agent.

Reference: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html

# Description of changes

Allows retention to be set to 1096 days

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests

None

# Requirements

1. Run `make fmt` and `make fmt-sh`

I did run these commands but they made changes to all sorts of files that I had not touched, so I did not commit these changes

2. Run `make linter`

This gave me:

```
fatal: No names found, cannot describe anything.
make: *** No rule to make target `linter'.  Stop.
```

### CODE REVIEW

**Comment by SaxyPandaBear** [comment]
I'm good with the change. Looks like the schema unit test is failing so would appreciate if you could fix that up. Longer term I think we might want to rethink if we want strict validation for this configuration from the agent or to just allow it to fail on the PutRetentionPolicy request

**Comment by markdboyd** [comment]
@SaxyPandaBear Thanks for the review! I believe that I fixed the failing unit test

**Review by sethAmazon — APPROVED** [review]
lgtm

**Review by SaxyPandaBear — APPROVED** [review]
LGTM

**Pull request merged**
