### PR TITLE
Add statsd.templates to the config json schema

### LINKED ISSUE #172: Custom global dimensions
Hi! Thank you for the software.
I'd like to ask what was the reason to forbid specifying custom global dimensions? I would like to add a global custom dimension `environment name: <env name>` for ALL metrics from cloudwatch agent for example. Yes, I can add it manually for most of agent inputs, but I can't do this for statsd and collectd, for example.

I'm talking about this part:

```
append_dimensions – Optional. Adds Amazon EC2 metric dimensions to all metrics collected by the agent. The only supported key-value pairs are shown in the following list. Any other key-value pairs are ignored.

"ImageID":"${aws:ImageId}" sets the instance's AMI ID as the value of the ImageID dimension.
"InstanceId":"${aws:InstanceId}" sets the instance's instance ID as the value of the InstanceID dimension.
"InstanceType":"${aws:InstanceType}" sets the instance's instance type as the value of the InstanceType dimension.
"AutoScalingGroupName":"${aws:AutoScalingGroupName}" sets the instance's Auto Scaling group name as the value of the AutoScalingGroupName dimension.
```

May be you are planning to add this feature or you can suggest any workaround.
Thanks!

### PR DESCRIPTION
**Pull request by matan129**
# Description of the issue
The statsd input module [supports](https://github.com/aws/amazon-cloudwatch-agent/blob/master/plugins/inputs/statsd/README.md) Telegraf style graphite templates, but these are blocked in the json schema.

Specifically, I've implemented this PR to resolve #172, but it adds additional capabilities to the agent beyond that (i.e. metric filtering, dynamic tagging, etc.) 

# Description of changes
This makes the config validator recognize the `templates` parameter, which is already supported by the statsd input module.

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
Note that the feature was already implemented, I merely enabled it to be configured. 
* Updated existing config tests
* Added basic tests for the new field

### CODE REVIEW

**Comment by matan129** [comment]
@jefchien @pxaws I'd appreciate a review here 🙏

**Comment by matan129** [comment]
@ZhenyuTan-amz ?

**Comment by matan129** [comment]
Anyone?
@haojhcwa @straussb ?

**Comment by jhnlsn** [comment]
Hey Matan,

thanks for the PR!  I'm going to discuss this with the team and get back to you.  We need to understand a little more about the impact of statsd templates as well as the original issue in #179

**Comment by matan129** [comment]
@jhnlsn Any updates on your side? 
Currently, I keep this fork alive for internal usage in my company and it's not so fun to maintain.

**Comment by matan129** [comment]
@jhnlsn any updates? This has been parked for a long time now.

**Comment by dxciberaws** [comment]
We feel this is needed to have some reasonable option to define meaningful alarms on CW on the custom metrics sent by the agent.

**Comment by matan129** [comment]
@jhnlsn ping

**Comment by khanhntd** [comment]
Hi @matan129, can you help us in explain the use case for the templates. However, as the [original issue ](https://github.com/aws/amazon-cloudwatch-agent/issues/172), there are similar PR to [support global dimension](https://github.com/aws/amazon-cloudwatch-agent/pull/673) and another thing to consider would be: Telegraf has a [concept of global tags](https://github.com/influxdata/telegraf/blob/53f36570fd2ecec058dfde207d5fc3fd7b8b7753/docs/CONFIGURATION.md#global-tags) which also solves the original issues. The templates is similar to a band-aid to specific plugin only.

**Comment by matan129** [comment]
It looks to me like the global dimensions PR indeed solves a superset of what my PR solves. Closing it.

**Pull request closed without merging**
