### PR TITLE
Delete runner cache and test cache if success

### PR DESCRIPTION
**Pull request by khanhntd**
# Description of the issue
Currently, there are two issues with time we got with:
* Should we build again even though the first retry has success? 
* The time for build is exactly the same without cache and with cache

# Description of changes
By changing these two,
* Adding cache to avoid building again for the second retry would reduce time and increase more resources spending on the remaining jobs
* Delete this path ```runner/Library/Caches/go-build``` when cache to reduce the time (testing it out with the PR) 

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
Test with a PR and found unexpected results without caching this path ```runner/Library/Caches/go-build```:
https://github.com/aws/amazon-cloudwatch-agent/runs/4990690788?check_suite_focus=true
https://github.com/aws/amazon-cloudwatch-agent/runs/4990745483?check_suite_focus=true

Compared when cached this path ```runner/Library/Caches/go-build```:
https://github.com/aws/amazon-cloudwatch-agent/runs/4990443776?check_suite_focus=true

### CODE REVIEW

**Comment by SaxyPandaBear** [comment]
Did you confirm that removing the macos cache path did not impact the build and test time?

**Comment by SaxyPandaBear** [comment]
BTW if you are running verifications on changes to the GitHub workflow, I think you could change the PR to a `Draft` state so that it can't be approved and merged. From when I did that for checking flaky tests in CI, you can still run GitHub workflows on a draft PR.

**Comment by khanhntd** [comment]
> Did you confirm that removing the macos cache path did not impact the build and test time?

Yes I have tested it and showed it in the description. For your convenience, here are the tests
* Without caching this path runner/Library/Caches/go-build:
https://github.com/aws/amazon-cloudwatch-agent/runs/4990690788?check_suite_focus=true
https://github.com/aws/amazon-cloudwatch-agent/runs/4990745483?check_suite_focus=true

* Compared when cached this path runner/Library/Caches/go-build:
https://github.com/aws/amazon-cloudwatch-agent/runs/4990443776?check_suite_focus=true

**Comment by khanhntd** [comment]
> BTW if you are running verifications on changes to the GitHub workflow, I think you could change the PR to a `Draft` state so that it can't be approved and merged. From when I did that for checking flaky tests in CI, you can still run GitHub workflows on a draft PR.

Nice tips though. Forgot that we could release a draft PR instead of filing one.

**Comment by jhnlsn** [comment]
Overall, I don't think you can skip building based on a cache hit.  the only thing we are caching is the output of the testing and the dependencies.  If code changes, it doesn't look like a new build/test will be triggered.

**Comment by khanhntd** [comment]
> Overall, I don't think you can skip building based on a cache hit. the only thing we are caching is the output of the testing and the dependencies. If code changes, it doesn't look like a new build/test will be triggered.

It only works when retrying the workflow instead of making a new commits. That's why we use ```github.run_id``` that would be unique between commits but will be the same when retrying the workflow.

**Comment by jhnlsn** [comment]
Ok, i see that now, which brings up another issue.  This means that you're only caching for the run, removing the original value of cache, which was to cache dependent packages and successful test runs so they didn't have to be downloaded again and the test didn't have to run again of no changes were made.

**Comment by jhnlsn** [comment]
Closing this out out in favor of breaking out each unit test workflow into its own flow

**Pull request closed without merging**
