### PR TITLE
Codecov file browser fix

### PR DESCRIPTION
**Pull request by jhnlsn**
# Description of the issue
Unable to view files on codecov

# Description of changes
Sets the correct base path to find files on github

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
_Describe what tests you have done._

### CODE REVIEW

**Review by SaxyPandaBear — APPROVED** [review]
I'm not sure how this lowered coverage but LGTM

**Comment by jhnlsn** [comment]
that change fixed it on my fork, but for some reason not here.  I'm going to do away with the running inside the folder.  not exactly sure why that was done in the first place.

**Comment by SaxyPandaBear** [comment]
I remember commenting on that before, because the action went into that folder in every step with a `cd`, so I suggested just using the working directory

**Comment by jhnlsn** [comment]
@SaxyPandaBear ready for review

**Review by SaxyPandaBear — APPROVED** [review]
LGTM

**Pull request merged**
