### PR TITLE
Sync Use crazy-max/ghaction-import-gpg@v5 From Private Repo

### PR DESCRIPTION
**Pull request by sethAmazon**
# Description of the issue
Fix gpg key singing

# Description of changes
Sync changes from private fork

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/3526117643

# Requirements
_Before commit the code, please do the following steps._
1. Run `make fmt` and `make fmt-sh`
2. Run `make linter`

### CODE REVIEW

**Comment by ChenaLee** [comment]
I'm guessing you are planning to sync again after the last fix is merged in private repo?

**Comment by sethAmazon** [comment]
Yes that is done

**Review by ChenaLee — APPROVED** [review]

**Review by khanhntd — COMMENTED** [review]
Is the error intended https://github.com/aws/amazon-cloudwatch-agent/actions/runs/3516817922/jobs/5893849503? and or there any security related issues we need to worry about though? Other than these two questions, LGTM.

**Review by khanhntd — APPROVED** [review]
LGTM (confirm with Seth that the PR has addressed the signing windows but will be more good to update the PR with correct run before merging to validate)

**Pull request merged**
