### PR TITLE
support onprem and onpremise and support windows msi installer w silent exec

### PR DESCRIPTION
**Pull request by aateeqi**
# Description of the issue
_Describe the problem or feature in addition to a link to the issues._

# Description of changes
_How does this change address the problem?_

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
_Describe what tests you have done._

# Requirements
_Before commit the code, please do the following steps._
1. Run `make fmt` and `make fmt-sh`
2. Run `make linter`

### CODE REVIEW

**Review by khanhntd — DISMISSED** [review]
LGTM.

**Review by adam-mateen — DISMISSED** [review]
approved

**Review by taohungyang — DISMISSED** [review]
LGTM

**Review by SaxyPandaBear — APPROVED** [review]

**Comment by SaxyPandaBear** [comment]
```
if grep --exclude-dir=build --exclude-dir=vendor -E "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}|(\"|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)(\"|')?\\s*(:|=>|=)\\s*(\"|')?[A-Za-z0-9/\\+=]{40}(\"|')?" -Rn .; then echo "check_secrets failed"; exit 1; fi;
./integration/msi/tools/amazon-cloudwatch-agent.wxs:31:                      Key="SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell"
```

Looks like we need to exclude the wxs file from check_secrets

**Review by SaxyPandaBear — APPROVED** [review]
LGTM. We might need to figure out a better way to exclude things going forward. Maybe setting up a githook. But not necessary to block this PR for that

**Review by adam-mateen — APPROVED** [review]

**Pull request merged**
