### PR TITLE
Upgrade Go SDK To Add Feature To Turn Off IMDSV1 Via ENV VAR

### PR DESCRIPTION
**Pull request by sethAmazon**
# Description of the issue
Could not turn on imdsv1 without code configuration of the agent. 

# Description of changes
Allow user to disable imdsv1 via an env var in the sdk. Upgrade the go sdk to a version that supports this feature. 

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
N/A

# Requirements
_Before commit the code, please do the following steps._
1. Run `make fmt` and `make fmt-sh`
2. Run `make lint`

### CODE REVIEW

**Review by okankoAMZ — APPROVED** [review]

**Comment by ZhenyuTan-amz** [comment]
Can we add a test to ensure v1 is disabled?

**Review by ZhenyuTan-amz — APPROVED** [review]
LGTM

**Comment by zhihonl** [comment]
Did we test using the environment variable that is supposed to disable IMDS V1? On Linux, the agent only read from systemd environment, so I assumed just doing `export` would not work and the customer has to manually modify the systemd setting.

**Comment by sethAmazon** [comment]
So I did test this against a preview version. You need to change the /etc/environment file

**Pull request merged**
